### ISSUE TITLE
Firefox Quantum Compatibility?

### ISSUE THREAD

**Issue by studiomantis** [mohd-akram/pip-vid#7] opened 2017-11-18 19:05 UTC
Im updated my Browser to the last version (Quantum). But the plugin don't have support yet.

Is in your road map to make this avaliable to this version too? 

![screen shot 2017-11-18 at 17 04 56](https://user-images.githubusercontent.com/28367400/32983860-b26f6b30-cc82-11e7-9719-15d263c05b5a.png)

**Comment by mohd-akram** [comment] 2017-11-19 14:20
WebExtensions don't support a borderless, always-on-top window right now. You can use [Min Vid](https://testpilot.firefox.com/experiments/min-vid/) which is a legacy add-on that doesn't have this restriction (because it's made by Mozilla). Closed as duplicate of #6.

**Closed as completed by mohd-akram** 2017-11-19 14:20 UTC
Labels: duplicate, question
